# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/george/Documents/ngcp/repos/NGCP_2021-2022/helloWorld/test_dualBareMetal/test_dualBareMetal.srcs/sources_1/bd/dualBareMetal_test/ip/dualBareMetal_test_xbar_0/dualBareMetal_test_xbar_0.xci
# IP: The module: 'dualBareMetal_test_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/george/Documents/ngcp/repos/NGCP_2021-2022/helloWorld/test_dualBareMetal/test_dualBareMetal.srcs/sources_1/bd/dualBareMetal_test/ip/dualBareMetal_test_xbar_0/dualBareMetal_test_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualBareMetal_test_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/george/Documents/ngcp/repos/NGCP_2021-2022/helloWorld/test_dualBareMetal/test_dualBareMetal.srcs/sources_1/bd/dualBareMetal_test/ip/dualBareMetal_test_xbar_0/dualBareMetal_test_xbar_0.xci
# IP: The module: 'dualBareMetal_test_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/george/Documents/ngcp/repos/NGCP_2021-2022/helloWorld/test_dualBareMetal/test_dualBareMetal.srcs/sources_1/bd/dualBareMetal_test/ip/dualBareMetal_test_xbar_0/dualBareMetal_test_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualBareMetal_test_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
