# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/george/Documents/ngcp/repos/NGCP_2021-2022/test_dualBareMetal/test_dualBareMetal.srcs/sources_1/bd/dualBareMetal_test/ip/dualBareMetal_test_axi_gpio_0_1/dualBareMetal_test_axi_gpio_0_1.xci
# IP: The module: 'dualBareMetal_test_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/george/Documents/ngcp/repos/NGCP_2021-2022/test_dualBareMetal/test_dualBareMetal.srcs/sources_1/bd/dualBareMetal_test/ip/dualBareMetal_test_axi_gpio_0_1/dualBareMetal_test_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualBareMetal_test_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/george/Documents/ngcp/repos/NGCP_2021-2022/test_dualBareMetal/test_dualBareMetal.srcs/sources_1/bd/dualBareMetal_test/ip/dualBareMetal_test_axi_gpio_0_1/dualBareMetal_test_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualBareMetal_test_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/george/Documents/ngcp/repos/NGCP_2021-2022/test_dualBareMetal/test_dualBareMetal.srcs/sources_1/bd/dualBareMetal_test/ip/dualBareMetal_test_axi_gpio_0_1/dualBareMetal_test_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualBareMetal_test_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/george/Documents/ngcp/repos/NGCP_2021-2022/test_dualBareMetal/test_dualBareMetal.srcs/sources_1/bd/dualBareMetal_test/ip/dualBareMetal_test_axi_gpio_0_1/dualBareMetal_test_axi_gpio_0_1.xci
# IP: The module: 'dualBareMetal_test_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/george/Documents/ngcp/repos/NGCP_2021-2022/test_dualBareMetal/test_dualBareMetal.srcs/sources_1/bd/dualBareMetal_test/ip/dualBareMetal_test_axi_gpio_0_1/dualBareMetal_test_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualBareMetal_test_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/george/Documents/ngcp/repos/NGCP_2021-2022/test_dualBareMetal/test_dualBareMetal.srcs/sources_1/bd/dualBareMetal_test/ip/dualBareMetal_test_axi_gpio_0_1/dualBareMetal_test_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualBareMetal_test_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/george/Documents/ngcp/repos/NGCP_2021-2022/test_dualBareMetal/test_dualBareMetal.srcs/sources_1/bd/dualBareMetal_test/ip/dualBareMetal_test_axi_gpio_0_1/dualBareMetal_test_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualBareMetal_test_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
