# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test.xdc

# Block Designs: bd/dualBareMetal_test/dualBareMetal_test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dualBareMetal_test || ORIG_REF_NAME==dualBareMetal_test} -quiet] -quiet

# IP: bd/dualBareMetal_test/ip/dualBareMetal_test_processing_system7_0_0/dualBareMetal_test_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dualBareMetal_test_processing_system7_0_0 || ORIG_REF_NAME==dualBareMetal_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/dualBareMetal_test/ip/dualBareMetal_test_xbar_0/dualBareMetal_test_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dualBareMetal_test_xbar_0 || ORIG_REF_NAME==dualBareMetal_test_xbar_0} -quiet] -quiet

# IP: bd/dualBareMetal_test/ip/dualBareMetal_test_ps7_0_axi_periph_0/dualBareMetal_test_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dualBareMetal_test_ps7_0_axi_periph_0 || ORIG_REF_NAME==dualBareMetal_test_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/dualBareMetal_test/ip/dualBareMetal_test_rst_ps7_0_50M_0/dualBareMetal_test_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dualBareMetal_test_rst_ps7_0_50M_0 || ORIG_REF_NAME==dualBareMetal_test_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/dualBareMetal_test/ip/dualBareMetal_test_axi_gpio_0_1/dualBareMetal_test_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dualBareMetal_test_axi_gpio_0_1 || ORIG_REF_NAME==dualBareMetal_test_axi_gpio_0_1} -quiet] -quiet

# IP: bd/dualBareMetal_test/ip/dualBareMetal_test_axi_gpio_1_1/dualBareMetal_test_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dualBareMetal_test_axi_gpio_1_1 || ORIG_REF_NAME==dualBareMetal_test_axi_gpio_1_1} -quiet] -quiet

# IP: bd/dualBareMetal_test/ip/dualBareMetal_test_auto_pc_0/dualBareMetal_test_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dualBareMetal_test_auto_pc_0 || ORIG_REF_NAME==dualBareMetal_test_auto_pc_0} -quiet] -quiet

# XDC: bd/dualBareMetal_test/dualBareMetal_test_ooc.xdc
